import { SideNavInterface } from './side-nav.type';

export const sideNavButtons: SideNavInterface[] = [
  {
    path: 'http://support.instigo.io/',
    title: 'Knowledgebase',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-books',
    submenu: [],
  },
];
export const sideNavRoutes: SideNavInterface[] = [
  {
    path: '',
    title: 'Manage',
    iconType: '',
    iconTheme: '',
    icon: '',
    submenu: [],
    type: 'title',
  },
  {
    path: '/dashboard/adaccount',
    title: 'Ad Account',
    iconType: 'fontawesome',
    icon: 'fa-ad',
    iconTheme: 'fas',
    submenu: [],
  },
  {
    path: null,
    title: 'Data Sync',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    callback: 'DATA_SYNC',
    icon: 'fa-sync-alt',
    submenu: [],
  },
  {
    path: '',
    title: 'Campaigns',
    iconType: '',
    iconTheme: '',
    icon: '',
    submenu: [],
    type: 'title',
  },
  {
    path: '/campaigns',
    title: 'Campaigns',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-bullseye',
    submenu: [],
  },
  {
    path: '/new-campaign',
    title: 'New Campaign',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-pen-fancy',
    submenu: [],
  },
  {
    path: '/campaign-draft',
    title: 'Campaign Drafts',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-save',
    submenu: [],
  },
  {
    path: '',
    title: 'Assets',
    iconType: '',
    iconTheme: '',
    icon: '',
    submenu: [],
    type: 'title',
  },
  {
    path: '/ad-templates',
    title: 'Ad Templates',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-sd-card',
    submenu: [],
    createPath: '/ad-templates/new',
  },
  {
    path: '/audiences',
    title: 'Audiences',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-user-friends',
    submenu: [],
    createPath: '/audiences/new',
  },
  {
    path: '/leadgen-form',
    title: 'Lead Forms',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'fa-file-alt',
    submenu: [],
  },
];
