import { customTooltip } from '../custom-tooltip';

// ! This file is currently not in use, and charts are generated by campaign-details.service.ts
// ! all logic should be copied to a shared service
export const chartMetrics = [
  {
    metric: ['spend', 'Spend'],
    axis: 'actionsSmall',
    colors: ['#7854f766', '#7854f7'],
    gradient: ['#7854f7', '#7854f70f', '#7854f701'],
    special: 'currency',
  },
  {
    metric: ['clicks', 'Clicks'],
    axis: 'actionsSmall',
    colors: ['#ffca0066', '#ffca00'],
    gradient: ['#ffca00', '#ffca000f', '#ffca0001'],
    special: 'bigNumber',
  },
  {
    metric: ['cpc', 'Cost per Click'],
    axis: 'cost',
    colors: ['#12a5ed66', '#12a5ed'],
    gradient: ['#12a5ed', '#12a5ed0f', '#12a5ed01'],
    special: 'currency',
  },
  {
    metric: ['frequency', 'Frequency'],
    axis: 'actionsSmall',
    colors: ['#7ed32166', '#7ed321'],
    gradient: ['#7ed321', '#7ed3210f', '#7ed32101'],
  },
  {
    metric: ['reach', 'Reach'],
    axis: 'actionsLarge',
    colors: ['#ff840066', '#ff8400'],
    gradient: ['#ff8400', '#ff84000f', '#ff840001'],
    special: 'bigNumber',
  },
  {
    metric: ['impressions', 'Impressions'],
    axis: 'actionsLarge',
    colors: ['#f5325b66', '#f5325b'],
    gradient: ['#f5325b', '#f5325b0f', '#f5325b01'],
    hidden: true,
    special: 'bigNumber',
  },
  {
    metric: ['ctr', 'Click Through Rate'],
    axis: 'percentage',
    colors: ['#ff69a566', '#ff69a5'],
    gradient: ['#ff69a5', '#ff69a50f', '#ff69a501'],
    hidden: true,
  },
  {
    metric: ['cpm', 'Cost per 1k Views'],
    axis: 'cost',
    colors: ['#5f63f266', '#5f63f2'],
    gradient: ['#5f63f2', '#5f63f20f', '#5f63f201'],
    special: 'currency',
    hidden: true,
  },
];

export const chartOptions = {
  scaleShowVerticalLines: false,
  maintainAspectRatio: true,
  responsive: true,
  legend: {
    display: false,
  },
  layout: {
    padding: {
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
  },
  tooltips: {
    mode: 'label',
    intersect: false,
    position: 'average',
    enabled: false,
    custom: customTooltip,
    callbacks: {
      label(t, d) {
        const dstLabel = d.datasets[t.datasetIndex].label;
        const { yLabel } = t;
        return `<span class="chart-data">${yLabel}</span> <span class="data-label">${dstLabel}</span>`;
      },
      labelColor(tooltipItem, chart) {
        const dataset = chart.config.data.datasets[tooltipItem.datasetIndex];
        return {
          backgroundColor: dataset.hoverBackgroundColor,
          borderColor: 'transparent',
          usePointStyle: true,
        };
      },
    },
  },
  scales: {
    yAxes: [
      {
        id: 'cost',
        type: 'linear',
        display: 'auto',
        position: 'left',
        gridLines: {
          color: '#e5e9f2',
          borderDash: [3, 3],
          zeroLineColor: '#e5e9f2',
          zeroLineWidth: 1,
          zeroLineBorderDash: [3, 3],
        },
        ticks: {
          callback: (v) => '€' + v,
        },
      },
      {
        id: 'costLarge',
        type: 'linear',
        display: 'auto',
        position: 'left',
        gridLines: {
          display: false,
          color: '#e5e9f2',
          borderDash: [3, 3],
          zeroLineColor: '#e5e9f2',
          zeroLineWidth: 1,
          zeroLineBorderDash: [3, 3],
        },
        ticks: {
          callback: (v) => '€' + v,
        },
      },
      {
        id: 'actionsSmall',
        type: 'linear',
        display: 'auto',
        position: 'right',
        gridLines: {
          display: false,
          color: '#e5e9f2',
          borderDash: [3, 3],
          zeroLineColor: '#e5e9f2',
          zeroLineWidth: 1,
          zeroLineBorderDash: [3, 3],
        },
      },
      {
        id: 'actionsLarge',
        type: 'linear',
        display: 'auto',
        position: 'right',
        gridLines: {
          display: false,
          color: '#e5e9f2',
          borderDash: [3, 3],
          zeroLineColor: '#e5e9f2',
          zeroLineWidth: 1,
          zeroLineBorderDash: [3, 3],
        },
      },
      {
        id: 'percentage',
        type: 'linear',
        display: 'auto',
        position: 'left',
        gridLines: {
          display: false,
          color: '#e5e9f2',
          borderDash: [3, 3],
          zeroLineColor: '#e5e9f2',
          zeroLineWidth: 1,
          zeroLineBorderDash: [3, 3],
        },
        ticks: {
          callback: (v) => v + '%',
        },
      },
    ],
    xAxes: [
      {
        gridLines: {
          display: true,
          zeroLineWidth: 2,
          zeroLineColor: '#fff',
          color: 'transparent',
          z: 1,
        },
        ticks: {
          beginAtZero: true,
          fontSize: 13,
          fontColor: '#182b49',
          stepSize: 3,
          autoSkip: true,
          maxTicksLimit: 10,
          maxRotation: 0,
        },
      },
    ],
  },
};
