export const QuickNavData = () => [
  {
    label: 'Dashboard',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'th-large',
    path: '/dashboard/workspace',
  },
  {
    label: 'New Campaign',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'layer-plus',
    path: '/new-campaign',
  },
  {
    label: 'Campaigns',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'megaphone',
    path: '/campaigns',
  },
  {
    label: 'Audiences',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'users-crown',
    path: '/audiences',
  },
  {
    label: 'Targeting Templates',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'poll-people',
    path: '/ad-templates',
  },
  {
    label: 'Ad Templates',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'swatchbook',
    path: '/ad-templates',
  },
  {
    label: 'Reports',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'file-chart-pie',
    path: '/reports',
  },
  {
    label: 'Optimizations',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'stream',
    path: '/optimizations',
  },
  {
    label: 'Networks',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'sitemap',
    path: '/networks',
  },
  {
    label: 'Automation',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'chart-line-down',
    path: '/automation',
  },
  {
    label: 'Automation',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'chart-line-down',
    path: '/automation',
  },
  {
    label: 'Settings',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'globe-europe',
    path: '/settings',
  },
  {
    label: 'Draft',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'edit',
    path: '/drafts',
  },
  {
    label: 'Tasks',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'folder',
    path: '/tasks',
  },
  {
    label: 'Services',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'list',
    path: '/services',
  },
  {
    label: 'Workspace Settings',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'list',
    path: '/account-control/workspaces',
  },
  {
    label: 'Create Ad Template',
    iconType: 'fontawesome',
    iconTheme: 'fas',
    icon: 'list',
    path: '/ad-templates',
  },
];
